# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mharris_ext}
  s.version = "1.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Harris"]
  s.date = %q{2009-12-17}
  s.description = %q{mharris717 utlity methods}
  s.email = %q{mharris717@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION.yml",
     "features/mharris_ext.feature",
     "features/steps/mharris_ext_steps.rb",
     "features/support/env.rb",
     "lib/mharris_ext.rb",
     "lib/mharris_ext/accessor.rb",
     "lib/mharris_ext/benchmark.rb",
     "lib/mharris_ext/cmd.rb",
     "lib/mharris_ext/enumerable.rb",
     "lib/mharris_ext/fileutils.rb",
     "lib/mharris_ext/from_hash.rb",
     "lib/mharris_ext/gems.rb",
     "lib/mharris_ext/methods.rb",
     "lib/mharris_ext/object.rb",
     "lib/mharris_ext/regexp.rb",
     "lib/mharris_ext/time.rb",
     "mharris_ext.gemspec",
     "test/mharris_ext_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/GFunk911/mharris_ext}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{mharris717 utility methods}
  s.test_files = [
    "test/mharris_ext_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fattr>, [">= 0"])
      s.add_runtime_dependency(%q<facets>, [">= 0"])
    else
      s.add_dependency(%q<fattr>, [">= 0"])
      s.add_dependency(%q<facets>, [">= 0"])
    end
  else
    s.add_dependency(%q<fattr>, [">= 0"])
    s.add_dependency(%q<facets>, [">= 0"])
  end
end
